version: '3.8'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: raidu
      MYSQL_USER: raidu
      MYSQL_PASSWORD: raidu1!
      MYSQL_ROOT_PASSWORD: raidu1!
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: goldenkiwi971202/myapp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/raidu
      SPRING_DATASOURCE_USERNAME: raidu
      SPRING_DATASOURCE_PASSWORD: raidu1!
      SPRING_PROFILES_ACTIVE: prod
    command: >
      sh -c "./wait-for-it.sh db:3306 -- java -jar /app/app.jar"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"  # Jenkins 포트 설정
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
