version: '3.8'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: raidu
      MYSQL_USER: raidu
      MYSQL_PASSWORD: raidu1!
      MYSQL_ROOT_PASSWORD: raidu1!
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    image: goldenkiwi971202/myapp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/raidu
      SPRING_DATASOURCE_USERNAME: raidu
      SPRING_DATASOURCE_PASSWORD: raidu1!
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: klmqskdlnpqncoqkwmdklcksoandfmklmqfmwqkdfcxnjkspring.application.name=raidu
      OPENVIDU_URL: https://i11a108.p.ssafy.io:4443/
      OPENVIDU_SECRET: z5F_hX2nQ-8rV3sW1dG7bM6tC
    command: >
      sh -c "./wait-for-it.sh db:3306 -- java -jar /app/app.jar"

  openvidu-server:
    image: openvidu/openvidu-server:2.30.0
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=z5F_hX2nQ-8rV3sW1dG7bM6tC
      - DOMAIN_OR_PUBLIC_IP=i11a108.p.ssafy.io
      - KMS_URIS=["ws://kms:8888/kurento"]
      - CERTIFICATE_TYPE=letsencrypt
      - LETSENCRYPT_EMAIL=goldenkiwi971202@gmail.com
      - HTTPS_PORT=4443
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - kms

  kms:
    image: kurento/kurento-media-server:latest
    ports:
      - "8888:8888"
      - "5000-5050:5000-5050/udp"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - app
      - openvidu-server

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080" # Jenkins 포트 설정
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home:
