version: '3.8'

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: raidu
      MYSQL_USER: raidu
      MYSQL_PASSWORD: raidu1!
      MYSQL_ROOT_PASSWORD: raidu1!
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: goldenkiwi971202/backend:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/raidu
      SPRING_DATASOURCE_USERNAME: raidu
      SPRING_DATASOURCE_PASSWORD: raidu1!
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: klmqskdlnpqncoqkwmdklcksoandfmklmqfmwqkdfcxnjkspring.application.name=raidu
      OPENVIDU_URL: https://i11a108.p.ssafy.io:4443/
      OPENVIDU_SECRET: z5F_hX2nQ-8rV3sW1dG7bM6tC
    command: >
      sh -c "./wait-for-it.sh db:3306 -- java -jar /app/app.jar"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8081" # Jenkins 포트 설정
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  jenkins_home: