OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD} # 여기에 실제 비밀번호를 입력하세요
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations : classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jwt:
    secret: klmqskdlnpqncoqkwmdklcksoandfmklmqfmwqkdfcxnjkspring.application.name=raidu

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourcompany.yourapp: DEBUG

server:
  port: 8080