OPENVIDU_URL: http://localhost:4443
OPENVIDU_SECRET: MY_SECRET

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raidu
    username: raidu
    password: raidu1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret: klmqskdlnpqncoqkwmdklcksoandfmklmqfmwqkdfcxnjkspring.application.name=raidu

  web:
    resources:
      static-locations: classpath:/public/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourcompany.yourapp: DEBUG

server:
  port: 8080
